### ISSUE TITLE
Xperia 5 IV "No available services matched the connected device." In EMMA

### ISSUE THREAD

**Issue by ywaf** [sonyxperiadev/device-sony-pdx224#2]
Hi,

I have a bricked 5iv after some aosp development, I would like to flash it back to stock, although the EMMA program is saying "No available services matched the connected device." when its plugged in. This is strange because the 5iv is in the open devices program, but seemingly an update hasnt been pushed to EMMA yet?

Just wondering when that would happen?

Thanks :)

**Comment by jerpelea** [comment]
What is the device model (XQ-CQxx) from your device box?

**Comment by ywaf** [comment]
XQ-CQ72

**Comment by jerpelea** [comment]
Unfortunately this is not a Global Generic device (supported by the project)

**Comment by ywaf** [comment]
so how would you recommend I flash back to stock? phone is currently bricked with the "device is corrupted" screen 😂

**Comment by jerpelea** [comment]
since this is an unsupported devices you can check the community flashtool or you can visit a the service point

**Comment by ywaf** [comment]
unfortunately, flashtool & newflasher weren't working and since this phone wasn't officially sold where I live, the service center doesn't want to take it (it was a grey import) :/

thanks anyway :)
